import Head from 'next/head';
import { useEffect, useState, type FormEvent } from 'react';
import { getServerSession } from 'next-auth/next';
import { signOut } from 'next-auth/react';
import type { GetServerSideProps } from 'next';
import { authOptions } from '@/lib/auth';
import { licenseStatus, type StudioData, type StudioLicense, type StudioScript } from '@/types/studio';
import s from '@/styles/studio.module.css';

type Props = { user: { id: string; name: string; role: 'owner' | 'client' } };
type View = 'overview' | 'licenses' | 'scripts';
type Modal = { kind: 'script' } | { kind: 'issue'; scriptId?: string } | { kind: 'upload'; scriptId: string } | { kind: 'delete'; script: StudioScript } | { kind: 'activate' | 'revoke' | 'detail'; license: StudioLicense };
export const getServerSideProps: GetServerSideProps<Props> = async ({ req, res }) => {
  res.setHeader('Cache-Control', 'private, no-store');
  const session = await getServerSession(req, res, authOptions);
  if (!session?.user?.id) return { redirect: { destination: '/login', permanent: false } };
  return { props: { user: { id: session.user.id, name: session.user.name || 'Cliente', role: session.user.role } } };
};
const labels = { overview: 'Visão geral', licenses: 'Licenças', scripts: 'Biblioteca' };
const statusLabels = { active: 'Ativa', pending: 'Pendente', revoked: 'Revogada', expired: 'Expirada' };
function Icon({ name, size = 20 }: { name: string; size?: number }) {
  const paths: Record<string, string> = { grid: 'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z', key: 'M14 3a7 7 0 0 0-6 10L2 19v3h4v-3h3v-3l2-2a7 7 0 1 0 3-11 M16 7h.01', box: 'M3 7l9-5 9 5v10l-9 5-9-5z M3 7l9 5 9-5 M12 12v10', arrow: 'M5 12h14 M13 6l6 6-6 6', plus: 'M12 4v16 M4 12h16', download: 'M12 3v12 M6 9l6 6 6-6 M3 17v4h18v-4', trash: 'M3 6h18 M9 6V3h6v3 M6 6l1 15h10l1-15 M10 10v7 M14 10v7', shield: 'M12 2l9 4v6c0 5-9 10-9 10S3 17 3 12V6z M8 12l3 3 5-6', refresh: 'M20 7a9 9 0 1 0 1 9 M20 2v6h-6', exit: 'M10 3H3v18h7 M8 12h13 M16 7l5 5-5 5', search: 'M21 21l-6-6 M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0', clock: 'M12 7v5l3 2 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0', copy: 'M8 8h13v13H8z M16 8V3H3v13h5', close: 'M5 5l14 14 M19 5L5 19' };
  return <svg width={size} height={size} viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.5' strokeLinecap='square' strokeLinejoin='miter' aria-hidden='true'><path d={paths[name] || paths.box}/></svg>;
}
function Emblem() { return <svg className={s.emblem} viewBox='0 0 420 300' fill='none' aria-hidden='true'><path d='M70 150L210 10l140 140-140 140z' stroke='#ff4655' strokeOpacity='.18'/><path d='M110 150L210 50l100 100-100 100z' stroke='#8aa6b3' strokeOpacity='.3'/><path d='M143 91h134l-32 40h-63v91l-39-40z' fill='#ff4655'/><path d='M199 148h65l-32 40h-33z' fill='#ece8e1'/><path d='M15 150h83 M322 150h83 M210 0v35 M210 265v35' stroke='#80929d' strokeOpacity='.35'/><circle cx='210' cy='150' r='128' stroke='#80929d' strokeDasharray='2 18' strokeOpacity='.4'/><path d='M45 70V40h30 M345 40h30v30 M45 230v30h30 M345 260h30v-30' stroke='#ff4655'/><text x='8' y='286' fill='#657982' fontSize='9' fontFamily='monospace'>PROTOCOL / ACCESS CONTROL</text><text x='333' y='18' fill='#ff4655' fontSize='9' fontFamily='monospace'>P—01</text></svg>; }
const dateLabel = (value?: string | null) => value ? new Date(value).toLocaleString('pt-BR', { dateStyle: 'short', timeStyle: 'short' }) : 'Vitalícia';
export default function Home({ user }: Props) {
  const owner = user.role === 'owner';
  const [view, setView] = useState<View>('overview'), [data, setData] = useState<StudioData | null>(null);
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [modal, setModal] = useState<Modal | null>(null), [query, setQuery] = useState(''), [filter, setFilter] = useState('all');
  const [duration, setDuration] = useState('30'), [now, setNow] = useState(Date.now());
  async function request(payload?: Record<string, unknown>) {
    const response = await fetch('/api/studio', payload ? { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) } : { cache: 'no-store' });
    if (response.status === 401) { window.location.assign('/login'); throw new Error('Sessão encerrada. Entre novamente.'); }
    const result = await response.json();
    if (!response.ok) throw new Error(result.error || 'Não foi possível acessar o painel.');
    setData(result); return result as StudioData;
  }
  async function refresh() { setBusy(true); setError(''); try { await request(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  useEffect(() => { void refresh(); const timer = setInterval(() => setNow(Date.now()), 30000); return () => clearInterval(timer); }, []);
  function open(next: Modal) { setError(''); setNotice(''); setDuration('30'); setModal(next); }
  function navigate(next: View) { setView(next); setQuery(''); setFilter('all'); }
  async function upload(file: File, scriptId: string) {
    const response = await fetch('/api/scripts/upload?id=' + encodeURIComponent(scriptId), { method: 'POST', headers: { 'Content-Type': 'application/zip' }, body: file });
    if (!response.ok) { const result = await response.json(); throw new Error(result.error || 'Falha no upload.'); }
  }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!modal || busy) return;
    const form = new FormData(event.currentTarget); const value = (name: string) => String(form.get(name) || '');
    setBusy(true); setError('');
    try {
      if (modal.kind === 'script' || modal.kind === 'upload') {
        const file = form.get('file');
        if (!(file instanceof File) || !file.size || !file.name.toLowerCase().endsWith('.zip')) throw new Error('Selecione um arquivo ZIP.');
        if (file.size > 3 * 1024 * 1024) throw new Error('O limite por ZIP é 3 MB.');
        let id = modal.kind === 'upload' ? modal.scriptId : '';
        if (modal.kind === 'script') {
          const result = await request({ action: 'script', name: value('name'), version: value('version'), description: value('description') });
          id = result.createdScriptId!;
          // Se o upload falhar, o próximo envio reutiliza o cadastro já criado.
          setModal({ kind: 'upload', scriptId: id });
        }
        await upload(file, id); await request();
      } else if (modal.kind === 'issue') {
        const expiresAt = duration === 'lifetime' ? null : duration === 'custom' ? new Date(value('expiresAt')).toISOString() : new Date(Date.now() + Number(duration) * 86400000).toISOString();
        await request({ action: 'issue', scriptId: value('scriptId'), discordId: value('discordId'), expiresAt });
      } else if (modal.kind === 'activate') await request({ action: 'activate', id: modal.license._id, binding: value('binding') });
      else if (modal.kind === 'delete') await request({ action: 'deleteScript', id: modal.script._id });
      else if (modal.kind === 'revoke') await request({ action: 'revoke', id: modal.license._id });
      setModal(null); setNotice('Operação concluída. Seus dados foram salvos.');
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  async function download(script: StudioScript) {
    setBusy(true); setError('');
    try { const response = await fetch('/api/scripts/download?id=' + encodeURIComponent(script._id)); if (!response.ok) { const result = await response.json(); throw new Error(result.error || 'Download indisponível.'); } const url = URL.createObjectURL(await response.blob()); const link = document.createElement('a'); link.href = url; link.download = script.fileName || 'script.zip'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
    catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  async function copy(text: string) { try { await navigator.clipboard.writeText(text); setNotice('Copiado para a área de transferência.'); } catch { setError('Não foi possível copiar. Abra os detalhes e selecione o texto.'); } }
  const licenses = data?.licenses || [], scripts = data?.scripts || [];
  const title = (license: StudioLicense) => scripts.find(x => x._id === license.scriptId)?.name || license.scriptName || 'Script removido';
  const rows = licenses.filter(l => (filter === 'all' || licenseStatus(l, now) === filter) && [title(l), l.discordId, l.key].join(' ').toLowerCase().includes(query.toLowerCase()));
  const shownScripts = scripts.filter(x => [x.name, x.version, x.description].join(' ').toLowerCase().includes(query.toLowerCase()));
  const active = licenses.filter(l => licenseStatus(l, now) === 'active').length;
  const pending = licenses.filter(l => licenseStatus(l, now) === 'pending').length;
  function badge(license: StudioLicense) { const state = licenseStatus(license, now); return <span className={`${s.badge} ${s[state]}`}><i/>{statusLabels[state]}</span>; }
  return <main className={s.desktop}><Head><title>{labels[view]} · Protocolo</title><meta name='theme-color' content='#0b141d'/></Head>
    <header className={s.topbar}><button className={s.brand} onClick={() => navigate('overview')}><span className={s.brandMark}>P</span><span>PROTOCOLO<small>LICENSE CONTROL SYSTEM</small></span></button><div className={s.topMeta}><span className={s.online}>● CONECTADO</span><div className={s.identity}><span>{user.name.slice(0, 2).toUpperCase()}</span><div><b>{user.name}</b><small>DISCORD VINCULADO</small></div><i/></div></div><button className={s.logout} onClick={() => void signOut({ callbackUrl: '/login' }).catch(() => setError('Não foi possível sair.'))}><Icon name='exit' size={17}/><span>Sair</span></button></header>
    <div className={s.layout}><aside className={s.sidebar}><div className={s.navLabel}>WORKSPACE <span>01</span></div><nav>{(Object.keys(labels) as View[]).map((v, i) => <button key={v} className={view === v ? s.selected : ''} aria-current={view === v ? 'page' : undefined} onClick={() => navigate(v)}><Icon name={['grid', 'key', 'box'][i]}/><span>{labels[v]}</span><small>0{i + 1}</small></button>)}</nav><div className={s.sidebarNote}><Icon name='shield' size={26}/><p>CONTROLE DE ACESSO</p><small>{owner ? 'Seu código. Suas regras.' : 'Seu acesso começa aqui.'}</small><div className={s.signal}><i/><i/><i/><i/><i/></div></div></aside>
    <section className={s.content}><div className={s.breadcrumb}><span>PROTOCOLO / {labels[view].toUpperCase()}</span><button disabled={busy} onClick={() => void refresh()}><Icon name='refresh' size={14}/>{busy ? 'SINCRONIZANDO' : 'ATUALIZAR'}</button></div>
      {error && !modal && <div className={s.error} role='alert'>{error}<button disabled={busy} onClick={() => void refresh()}>Tentar novamente</button></div>}
      {notice && <div className={s.notice} role='status'><Icon name='shield' size={16}/>{notice}<button onClick={() => setNotice('')} aria-label='Fechar aviso'>×</button></div>}
      {view === 'overview' ? <><section className={s.hero}><div className={s.heroCopy}><p className={s.eyebrow}><i/> CENTRAL DE OPERAÇÕES</p><h1>SEU CÓDIGO.<br/><em>SOB CONTROLE.</em></h1><p>Bem-vindo, {user.name}. {owner ? 'Gerencie seu arsenal de scripts e defina quem tem acesso.' : 'Acesse seus scripts, libere suas licenças e entre em operação.'}</p><div className={s.heroActions}><button className={s.primary} disabled={busy || !data} onClick={() => owner ? open({ kind: scripts.length ? 'issue' : 'script' }) : navigate('licenses')}>{owner ? scripts.length ? 'GERAR LICENÇA' : 'PUBLICAR SCRIPT' : 'MINHAS LICENÇAS'}<Icon name='arrow' size={18}/></button><button className={s.textButton} onClick={() => navigate('scripts')}>EXPLORAR BIBLIOTECA ↗</button></div></div><div className={s.heroArt}><Emblem/><span>SISTEMA DE LICENÇAS / V.02</span></div></section>
      <div className={s.stats}>{[['key', 'TOTAL DE LICENÇAS', licenses.length, 'Registros no workspace'], ['shield', 'LICENÇAS ATIVAS', active, 'Acesso liberado'], ['clock', 'PENDENTES', pending, 'Aguardando ativação'], ['box', 'SCRIPTS PUBLICADOS', scripts.length, 'Na sua biblioteca']].map(([icon, label, count, hint], i) => <article className={s.stat} key={label}><div><span>{label}</span><Icon name={String(icon)} size={17}/></div><strong>{data ? String(count).padStart(2, '0') : '—'}</strong><small><i className={i === 1 ? s.greenDot : ''}/>{hint}</small><span className={s.statNumber}>0{i + 1}</span></article>)}</div></> : <div className={s.pageHeading}><div><p className={s.eyebrow}>WORKSPACE / {view === 'scripts' ? '03' : '02'}</p><h1>{view === 'scripts' ? 'BIBLIOTECA DE SCRIPTS' : 'CONTROLE DE LICENÇAS'}</h1><p>{view === 'scripts' ? 'Seu catálogo. Pronto para entrar em operação.' : 'Gerencie o acesso, a validade e o status de cada chave.'}</p></div>{owner && <button className={s.primary} disabled={busy || !data || (view === 'licenses' && !scripts.length)} onClick={() => open({ kind: view === 'scripts' ? 'script' : 'issue' })}><Icon name='plus' size={16}/>{view === 'scripts' ? 'PUBLICAR SCRIPT' : 'GERAR LICENÇA'}</button>}</div>}
      {view !== 'scripts' ? <section className={s.panel}><div className={s.panelHead}><div><p className={s.eyebrow}>REGISTRO DE ACESSOS</p><h2>{view === 'overview' ? 'LICENÇAS RECENTES' : 'SUAS LICENÇAS'} <span>{data ? licenses.length : '—'}</span></h2></div>{view === 'overview' ? <button className={s.textButton} onClick={() => navigate('licenses')}>VER TODAS <Icon name='arrow' size={16}/></button> : <label className={s.search}><Icon name='search' size={16}/><input aria-label='Buscar licenças' value={query} onChange={e => setQuery(e.target.value)} placeholder='Buscar script, ID ou chave'/></label>}</div>
      {view === 'licenses' && <div className={s.filters}>{[['all', 'Todas'], ['active', 'Ativas'], ['pending', 'Pendentes'], ['expired', 'Expiradas'], ['revoked', 'Revogadas']].map(([value, label]) => <button key={value} aria-pressed={filter === value} className={filter === value ? s.filterActive : ''} onClick={() => setFilter(value)}>{label}</button>)}</div>}
      <div className={s.tableWrap}><table><thead><tr><th>SCRIPT / CHAVE</th>{owner && <th>CLIENTE DISCORD</th>}<th>STATUS</th><th>EXPIRAÇÃO</th><th>SERVIDOR</th><th>CONTROLE</th></tr></thead><tbody>{(view === 'overview' ? rows.slice(0, 5) : rows).map(l => <tr key={l._id}><td><button className={s.scriptCell} onClick={() => open({ kind: 'detail', license: l })}><span><Icon name='key' size={18}/></span><div><b>{title(l)}</b><code>{l.key.slice(0, 16)}••••</code></div></button></td>{owner && <td><code>{l.discordId}</code></td>}<td>{badge(l)}</td><td>{dateLabel(l.expiresAt)}</td><td>{l.binding || 'Não vinculado'}</td><td><div className={s.rowActions}><button title='Copiar chave' aria-label={'Copiar chave de ' + title(l)} onClick={() => void copy(l.key)}><Icon name='copy' size={16}/></button>{licenseStatus(l, now) === 'pending' && <button disabled={busy} onClick={() => open({ kind: 'activate', license: l })}>Liberar ↗</button>}{owner && l.status !== 'revoked' && <button className={s.dangerText} disabled={busy} onClick={() => open({ kind: 'revoke', license: l })}>Revogar</button>}<button onClick={() => open({ kind: 'detail', license: l })} aria-label={'Detalhes de ' + title(l)}>↗</button></div></td></tr>)}</tbody></table></div>
      {!rows.length && <div className={s.empty}><Icon name='key' size={36}/><h3>{!data ? busy ? 'CONECTANDO AO WORKSPACE' : 'DADOS INDISPONÍVEIS' : licenses.length ? 'NENHUM RESULTADO' : 'NENHUMA LICENÇA EM OPERAÇÃO'}</h3><p>{!data ? 'Os registros aparecerão após a sincronização.' : licenses.length ? 'Ajuste sua busca ou escolha outro status.' : owner ? 'Publique um script e gere a primeira chave de acesso.' : 'As licenças emitidas para seu Discord aparecerão aqui.'}</p>{owner && data && !licenses.length && <button className={s.secondary} onClick={() => open({ kind: scripts.length ? 'issue' : 'script' })}>{scripts.length ? 'GERAR LICENÇA' : 'PUBLICAR SCRIPT'} <Icon name='plus' size={16}/></button>}</div>}
      <div className={s.panelFoot}><span><Icon name='shield' size={12}/> {owner ? 'CONTROLE DO PROPRIETÁRIO' : 'ACESSO INDIVIDUAL'}</span><span>{data ? `${rows.length} REGISTRO(S)` : 'AGUARDANDO DADOS'}</span></div></section> : <><div className={s.libraryTools}><span>{data ? scripts.length : '—'} SCRIPT(S) NO CATÁLOGO</span><label className={s.search}><Icon name='search' size={16}/><input aria-label='Buscar scripts' value={query} onChange={e => setQuery(e.target.value)} placeholder='Buscar na biblioteca'/></label></div><div className={s.scripts}>{shownScripts.map((script, index) => { const canDownload = owner || licenses.some(l => l.scriptId === script._id && licenseStatus(l, now) === 'active'); return <article className={s.scriptCard} key={script._id}><div className={s.scriptVisual}><span>ASSET / {String(index + 1).padStart(3, '0')}</span><Icon name='box' size={68}/><b>{script.version}</b></div><div className={s.scriptBody}><p className={s.eyebrow}>{script.hasDownload ? 'PACOTE DISPONÍVEL' : 'ZIP PENDENTE'}</p><h2>{script.name}</h2><p>{script.description || 'Sem descrição.'}</p><div className={s.scriptMeta}><span>{licenses.filter(l => l.scriptId === script._id).length} licença(s)</span><span>{script.fileSize ? (script.fileSize / 1024).toFixed(0) + ' KB' : '—'}</span></div><div className={s.cardActions}>{owner && <button className={s.primary} disabled={busy} onClick={() => open({ kind: 'issue', scriptId: script._id })}>GERAR LICENÇA<Icon name='key' size={15}/></button>}<button className={s.secondary} disabled={busy || !script.hasDownload || !canDownload} title={!canDownload ? 'Ative sua licença para baixar' : 'Baixar ZIP'} onClick={() => void download(script)}><Icon name='download' size={16}/>{owner ? 'ZIP' : 'BAIXAR SCRIPT'}</button></div>{owner && <div className={s.scriptAdmin}><button onClick={() => open({ kind: 'upload', scriptId: script._id })}>{script.hasDownload ? 'Substituir ZIP' : 'Enviar ZIP'}</button><button className={s.dangerText} onClick={() => open({ kind: 'delete', script })}><Icon name='trash' size={13}/>Excluir script</button></div>}</div></article>; })}</div>{!shownScripts.length && <div className={s.empty}><Icon name='box' size={38}/><h3>{data ? 'BIBLIOTECA VAZIA' : 'CARREGANDO BIBLIOTECA'}</h3><p>{query ? 'Nenhum script corresponde à busca.' : owner ? 'Publique seu primeiro pacote ZIP para começar.' : 'Seus scripts licenciados aparecerão aqui.'}</p></div>}</>}
      <footer className={s.footer}><b>PROTOCOLO <span>© {new Date(now).getFullYear()}</span></b><span>LICENSE CONTROL SYSTEM <i/> DISCORD AUTHENTICATED</span></footer>
    </section></div>
    {modal && <dialog className={s.modal} aria-labelledby='modal-title' ref={node => { if (node && !node.open) node.showModal(); }} onCancel={e => { if (busy) e.preventDefault(); else { setModal(null); setError(''); } }}><div className={s.modalHeader}><p className={s.eyebrow}>PROTOCOLO / CONTROLE</p><button disabled={busy} aria-label='Fechar' onClick={() => { setModal(null); setError(''); }}><Icon name='close'/></button></div><h2 id='modal-title'>{{ script: 'PUBLICAR SCRIPT', issue: 'GERAR LICENÇA', upload: 'ENVIAR PACOTE ZIP', delete: 'EXCLUIR SCRIPT', activate: 'LIBERAR LICENÇA', revoke: 'REVOGAR LICENÇA', detail: 'DADOS DA LICENÇA' }[modal.kind]}</h2>
      {modal.kind === 'detail' ? <><div className={s.detailTop}><h3>{title(modal.license)}</h3>{badge(modal.license)}</div><dl className={s.details}><div><dt>Script ID</dt><dd>{modal.license.scriptId}</dd></div><div><dt>Discord</dt><dd>{modal.license.discordId}</dd></div><div><dt>Servidor</dt><dd>{modal.license.binding || 'Não vinculado'}</dd></div><div><dt>Criada em</dt><dd>{dateLabel(modal.license.createdAt)}</dd></div><div><dt>Expiração</dt><dd>{dateLabel(modal.license.expiresAt)}</dd></div><div><dt>Última validação</dt><dd>{modal.license.lastValidatedAt ? dateLabel(modal.license.lastValidatedAt) : 'Ainda não validada'}</dd></div></dl><p className={s.eyebrow}>CHAVE DE ACESSO</p><code className={s.fullKey}>{modal.license.key}</code><button className={s.primary} onClick={() => void copy(modal.license.key)}>COPIAR CHAVE <Icon name='copy' size={16}/></button>{notice && <p role='status' className={s.formHelp}>{notice}</p>}{error && <p role='alert' className={s.error}>{error}</p>}</> : <form onSubmit={submit}>
      {modal.kind === 'script' && <><label>Nome do script<input name='name' required maxLength={120} autoFocus placeholder='Ex.: Advanced Inventory'/></label><label>Versão<input name='version' required defaultValue='1.0.0' maxLength={30}/></label><label>Descrição<textarea name='description' maxLength={1000} placeholder='O que esse script oferece?'/></label></>}
      {(modal.kind === 'script' || modal.kind === 'upload') && <label className={s.fileField}><Icon name='box' size={25}/><span>PACOTE DO SCRIPT</span><input name='file' type='file' accept='.zip,application/zip' required/><small>Arquivo ZIP de até 3 MB. Download protegido por licença ativa.</small></label>}
      {modal.kind === 'issue' && <><label>Script<select name='scriptId' defaultValue={modal.scriptId || scripts[0]?._id} required>{scripts.map(script => <option value={script._id} key={script._id}>{script.name} · v{script.version}</option>)}</select></label><label>ID do Discord do cliente<input name='discordId' autoFocus required pattern='[0-9]{17,20}' maxLength={20} placeholder='ID numérico da conta Discord'/></label><label>Validade<select value={duration} onChange={e => setDuration(e.target.value)}><option value='7'>7 dias</option><option value='30'>30 dias</option><option value='90'>90 dias</option><option value='365'>1 ano</option><option value='lifetime'>Vitalícia</option><option value='custom'>Data e hora personalizadas</option></select></label>{duration === 'custom' && <label>Expira em (seu horário local)<input name='expiresAt' type='datetime-local' required/></label>}<p className={s.formHelp}>A validade começa na emissão. A chave será gerada no servidor e vinculada ao Discord informado.</p></>}
      {modal.kind === 'activate' && <><p className={s.formHelp}>Vincule a licença de <b>{title(modal.license)}</b> ao servidor que usará o script.</p><label>Identificação do servidor<input name='binding' required maxLength={120} autoFocus placeholder='Ex.: meu-servidor-01'/></label><p className={s.formHelp}>Use exatamente esta identificação na integração de validação do script.</p></>}
      {modal.kind === 'delete' && <p className={s.confirmText}>Excluir <b>{modal.script.name}</b> da biblioteca? O download será bloqueado e todas as licenças deste script serão revogadas. O histórico será preservado.</p>}
      {modal.kind === 'revoke' && <p className={s.confirmText}>Revogar a licença de <b>{title(modal.license)}</b>? Ela deixará de validar e não permitirá novos downloads. Esta chave não poderá ser reativada.</p>}
      {error && <p className={s.error} role='alert'>{error}</p>}<div className={s.formActions}><button type='button' disabled={busy} className={s.secondary} onClick={() => { setModal(null); setError(''); }}>CANCELAR</button><button className={s.primary} disabled={busy}>{busy ? 'PROCESSANDO…' : modal.kind === 'delete' ? 'EXCLUIR E REVOGAR' : modal.kind === 'revoke' ? 'REVOGAR LICENÇA' : modal.kind === 'issue' ? 'GERAR CHAVE' : modal.kind === 'activate' ? 'LIBERAR ACESSO' : 'PUBLICAR'}<Icon name='arrow' size={16}/></button></div></form>}
    </dialog>}
  </main>;
}
