const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const ts=require('typescript');
const context={exports:{},Date};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('types/studio.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,context);
const status=context.exports.licenseStatus;
const now=Date.now();
assert.equal(status({status:'active'},now),'active');
assert.equal(status({status:'active',expiresAt:null},now),'active');
assert.equal(status({status:'pending',expiresAt:new Date(now+1).toISOString()},now),'pending');
assert.equal(status({status:'active',expiresAt:new Date(now).toISOString()},now),'expired');
assert.equal(status({status:'pending',expiresAt:new Date(now-1).toISOString()},now),'expired');
assert.equal(status({status:'revoked',expiresAt:new Date(now-1).toISOString()},now),'revoked');
console.log('PASS: expiration boundary, pending expiration, lifetime/legacy records and revocation precedence.');
